using Robust.Shared.GameStates;

namespace Content.Server._AS.Shuttles.Deeds;

/// <summary>
///     A component that attempts to generate a deed on the given entity when initialized
/// </summary>
[RegisterComponent]
public sealed partial class AutoGenerateDeedComponent : Component
{

    /// <summary>
    ///     If true, on generation all other shuttle deeds that link to the targeted entity will be removed.
    /// </summary>
    [DataField("Unique")]
    public bool Unique = false;

    /// <summary>
    ///     If null, the deed will attempt to generate on whatever grid it is parented too, otherwise it will try to find a grid of the given name and assign the Deed to that.
    /// </summary>
    [DataField("StationName")]
    public string? StationName = null;

}
