using System.Linq;
using Content.Server.Station.Components;
using Content.Shared._AS.Shuttles.Deeds;
using Content.Shared._NF.Shipyard.Components;
using Content.Shared.Access.Components;
using Content.Shared.Station.Components;

namespace Content.Server._AS.Shuttles.Deeds;

public sealed partial class AutoGenerateDeedSystem : SharedAutoGenerateDeedSystem
{
    public override void Initialize()
    {
        base.Initialize();
        SubscribeLocalEvent<AutoGenerateDeedComponent, ComponentStartup>(OnComponentStartup);
    }

    private void OnComponentStartup(EntityUid uid, AutoGenerateDeedComponent component, ComponentStartup args)
    {

        EntityUid? grid = null;
        if (component.StationName != null) // Logic for pre-defined auto generating deeds that point to POI's
        {
            var query = EntityQueryEnumerator<StationDataComponent, MetaDataComponent>();
            while (query.MoveNext(out var stationUid, out var _, out var metaData)) // Find the station that matches what we are given
            {
                if (component.StationName == metaData.EntityName) // This works under the assumption that majour stations can't be renamed.
                {
                    Log.Debug($"AssignDeeds called with iduid={uid}, shuttleuid={stationUid}, name={metaData.EntityName}");
                    AssignDeeds(uid, stationUid, metaData, false, false);
                    grid = stationUid;
                    break; // If theres somehow two POI's with the same name, cry a little
                }
            }
        }
        else // Logic for auto generating deeds that can be spawned on any viable grid to generate it a Deed
        {
            if (TryComp<TransformComponent>(uid, out var transform) && transform.GridUid is { } gridUid) // Get the grid of whatever we are on
            {
                if (TryComp<MetaDataComponent>(transform.GridUid, out var shuttleMeta) && TryComp<StationMemberComponent>(transform.GridUid, out var stationMember)) // Figure out if its a station
                {
                    Log.Debug($"AssignDeeds called with iduid={uid}, shuttleuid={gridUid}, name={shuttleMeta.EntityName}");
                    AssignDeeds(uid, gridUid, shuttleMeta, component.Unique, true);
                    grid = transform.GridUid;
                }
            }
        }

        if (grid == null)
        {
            Log.Error($"Deed autogeneration failed for entity {uid}, parameters: {component.StationName}");
            return;
        }

        if (component.Unique)
        {
            var query = EntityQueryEnumerator<ShuttleDeedComponent, IdCardComponent>();
            while (query.MoveNext(out var otherId, out var deed, out var _)) // If this is a unique shuttle deed, we want to remove the deed from any other ID's that link to our grid
            {
                if (uid == otherId) // Don't want to wipe our ID
                    continue;
                if (deed.ShuttleUid == grid)
                    RemComp<ShuttleDeedComponent>(otherId);
            }
        }
    }
}
