using Content.Server._AS.Deeds.Components;
using Content.Server.Station.Components;
using Content.Shared.Access.Components;
using Content.Shared.Station.Components;
using Content.Shared._NF.Shipyard.Components;
using Robust.Shared.GameObjects;
using Robust.Shared.Log;
using System.Linq;

namespace Content.Server._AS.Deeds.Systems;

public sealed partial class AutoGenerateDeedSystem : EntitySystem
{
    public override void Initialize()
    {
        base.Initialize();
        SubscribeLocalEvent<AutoGenerateDeedComponent, ComponentStartup>(OnComponentStartup);
    }

    private void OnComponentStartup(EntityUid uid, AutoGenerateDeedComponent component, ComponentStartup args)
    {

        EntityUid? grid = null;
        if (component.StationName != null) // Logic for pre-defined auto generating deeds that point to POI's
        {
            var query = EntityQueryEnumerator<StationDataComponent, MetaDataComponent>();
            while (query.MoveNext(out var stationUid, out var _, out var metaData)) // Find the station that matches what we are given
            {
                if (component.StationName != metaData.EntityName) // This works under the assumption that majour stations can't be renamed.
                {
                    AssignDeeds(uid, stationUid, metaData, false, false);
                    grid = stationUid;
                    break; // If theres somehow two POI's with the same name, cry a little
                }
            }
        }
        else // Logic for auto generating deeds that can be spawned on any viable grid to generate it a Deed
        {
            if (TryComp<TransformComponent>(uid, out var transform) && transform.GridUid is { } gridUid) // Get the grid of whatever we are on
            {
                if (TryComp<MetaDataComponent>(transform.GridUid, out var shuttleMeta) && TryComp<StationMemberComponent>(transform.GridUid, out var stationMember)) // Figure out if its a station
                {
                    AssignDeeds(uid, gridUid, shuttleMeta, component.Unique, true);
                    grid = transform.GridUid;
                }
            }
        }

        if (grid == null)
        {
            Log.Error($"Deed autogeneration failed for entity {uid}, parameters: {component.StationName}");
            return;
        }

        if (component.Unique)
        {
            var query = EntityQueryEnumerator<ShuttleDeedComponent, IdCardComponent>();
            while (query.MoveNext(out var otherID, out var deed, out var _)) // If this is a unique shuttle deed, we want to remove the deed from any other ID's that link to our grid
            {
                if (uid == otherID) // Don't want to wipe our ID
                    continue;
                if (deed.ShuttleUid == grid)
                    RemComp<ShuttleDeedComponent>(otherID);
            }
        }
    }
    private void AssignDeeds(EntityUid iduid, EntityUid shuttleuid, MetaDataComponent shuttlemeta, bool sellable, bool shuttle)
    {
        var deedID = EnsureComp<ShuttleDeedComponent>(iduid);
        if (shuttle) // Shuttles have fancier names
            ParseShuttleName(deedID, shuttlemeta.EntityName);
        else
            deedID.ShuttleName = shuttlemeta.EntityName;
        deedID.ShuttleUid = shuttleuid;
        deedID.Sellable = sellable;

        Entity<ShuttleDeedComponent> ent = (iduid, deedID);
        Dirty(ent);

        var deedStation = EnsureComp<ShuttleDeedComponent>(shuttleuid);
        if (shuttle) // Shuttles have fancier names
            ParseShuttleName(deedStation, shuttlemeta.EntityName);
        else
            deedID.ShuttleName = shuttlemeta.EntityName;
        deedStation.ShuttleUid = shuttleuid;
        deedStation.Sellable = sellable;
    }
    private void ParseShuttleName(ShuttleDeedComponent deed, string name) // Taken from ShipyardSystem.Consoles.cs "TryParseShuttleName"
    {
        // The logic behind this is: if a name part fits the requirements, it is the required part. Otherwise it's the name.
        // This may cause problems but ONLY when renaming a ship. It will still display properly regardless of this.
        var nameParts = name.Split(' ');

        var hasSuffix = nameParts.Length > 1 && nameParts.Last().Length < ShuttleDeedComponent.MaxSuffixLength && nameParts.Last().Contains('-');
        deed.ShuttleNameSuffix = hasSuffix ? nameParts.Last() : null;
        deed.ShuttleName = String.Join(" ", nameParts.SkipLast(hasSuffix ? 1 : 0));
    }
}
