using System.Linq;

namespace Content.Shared._AS.Shuttles.Deeds;
using Content.Shared._NF.Shipyard.Components;

public partial class SharedAutoGenerateDeedSystem : EntitySystem
{
    protected void AssignDeeds(EntityUid iduid, EntityUid shuttleuid, MetaDataComponent shuttlemeta, bool sellable, bool shuttle)
    {
        var deedId = EnsureComp<ShuttleDeedComponent>(iduid);
        if (shuttle) // Shuttles have fancier names
            ParseShuttleName(deedId, shuttlemeta.EntityName);
        else
            deedId.ShuttleName = shuttlemeta.EntityName;
        deedId.ShuttleUid = shuttleuid;
        deedId.Sellable = sellable;

        Entity<ShuttleDeedComponent> ent = (iduid, deedId);
        Dirty(ent);

        var deedStation = EnsureComp<ShuttleDeedComponent>(shuttleuid);
        if (shuttle) // Shuttles have fancier names
            ParseShuttleName(deedStation, shuttlemeta.EntityName);
        else
            deedId.ShuttleName = shuttlemeta.EntityName;
        deedStation.ShuttleUid = shuttleuid;
        deedStation.Sellable = sellable;
    }

    private void ParseShuttleName(ShuttleDeedComponent deed, string name) // Taken from ShipyardSystem.Consoles.cs "TryParseShuttleName"
    {
        // The logic behind this is: if a name part fits the requirements, it is the required part. Otherwise it's the name.
        // This may cause problems but ONLY when renaming a ship. It will still display properly regardless of this.
        var nameParts = name.Split(' ');

        var hasSuffix = nameParts.Length > 1 && nameParts.Last().Length < ShuttleDeedComponent.MaxSuffixLength && nameParts.Last().Contains('-');
        deed.ShuttleNameSuffix = hasSuffix ? nameParts.Last() : null;
        deed.ShuttleName = String.Join(" ", nameParts.SkipLast(hasSuffix ? 1 : 0));
    }
}
