# Leader
- type: job
  id: CAFLeader
  name: job-name-cafleader
  description: job-description-cafleader
  playTimeTracker: JobCAFLeader
  setPreference: false
  startingGear: CAFLeaderGearEVA
  icon: "JobIconColonialArmedForces"
  supervisors: job-supervisors-colcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - ColonialCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantColcomm ]
  whitelisted: true

#- type: startingGear # TODO: add later
#  id: CAFLeaderGear
#  equipment:
#    jumpsuit: ClothingUniformJumpsuitERTLeader
#    back: ClothingBackpackERTLeader
#    shoes: ClothingShoesBootsCombatFilled
#    head: ClothingHeadHelmetERTLeader
#    eyes: ClothingEyesGlassesSecurity
#    gloves: ClothingHandsGlovesCombat
#    outerClothing: ClothingOuterArmorBasicSlim
#    id: ERTLeaderPDA
#    ears: ClothingHeadsetAltCentCom
#    belt: ClothingBeltSecurityFilled
#    pocket1: NFWeaponPistolN1984 # Frontier
#    pocket2: FlashlightSeclite
#  storage:
#    back:
#    - NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
#    - MedicatedSuture
#    - RegenerativeMesh
#    - BoxZiptie
#    - CrowbarRed
#    - NFMagazinePistol45 # Frontier: MagazineMagnum<NFMagazinePistol45

- type: startingGear
  id: CAFLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryCAFLeader
    back: ClothingBackpackCAFLeader
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasCAF
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitMilitaryCAFLeader
    id: CAFLeaderPDA
    ears: ClothingHeadsetAltColCom
    belt: ClothingBeltMilitaryWebbingSecurityFilled
    pocket1: NFWeaponPistolN1984 # Frontier
    pocket2: FlashlightSeclite
  storage:
    back:
    - NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - NFMagazinePistol45 # Frontier: MagazineMagnum<NFMagazinePistol45

- type: startingGear
  id: CAFLeaderGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryCAFLeader
    back: ClothingBackpackCAFLeader
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasCAF
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitMilitaryCAFLeader
    id: CAFLeaderPDA
    ears: ClothingHeadsetAltColCom
    belt: ClothingBeltMilitaryWebbingSecurityFilled
    pocket1: NFMagazineRifle20 # Frontier: MagazineRifle<NFMagazineRifle20
    pocket2: NFMagazineRifle20 # Frontier: MagazineRifle<NFMagazineRifle20
  inhand:
  - NFWeaponRifleAssaultLecter # Frontier: WeaponRifleLecter<NFWeaponRifleAssaultLecter
  storage:
    back:
    - NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - NFMagazinePistol45 # Frontier: MagazineMagnum<NFMagazinePistol45

#- type: chameleonOutfit # TODO: add later
#  id: CAFLeaderChameleonOutfit
#  job: CAFLeader
#  hasMindShield: true
#  equipment:
#    head: ClothingHeadHelmetHardsuitERTLeader
#    neck: ClothingNeckBronzeheart
