using Content.Shared._NF.Shipyard.Components;
using Robust.Shared.GameStates;

namespace Content.Server._NF.Shipyard.Components;

// AS
/// <summary>
/// Tied to an ID card when a ship is purchased. 1 ship per captain.
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
[Access(typeof(AutoGenerateDeedSystem))]
public sealed partial class ShuttleDeedComponent : SharedShuttleDeedComponent
{
}